### ISSUE TITLE
Keep LLM running instead of loading new per chat

### ISSUE THREAD

**Issue by Arthur2500** [ollama-webui/ollama-webui-lite#18]
**Is your feature request related to a problem? Please describe.**
Whenever I close a chat or close the website, after a threshold ollama stops the used model. That leads to longer waiting times for answers as the model needs to be loaded on every new chat/request

**Describe the solution you'd like**
A way to set the default model to be "always running", like the `ollama run` command. If another model is requested the default model may get shut down for the other model to run. after the other model is unused, the default model gets ran again to always be responsive

**Describe alternatives you've considered**
A simple `ollama run` in another terminal window fixes it, but if another model is requested the load is too high as both models run in parallel i believe

**Additional context**
chatgpts responses for example are imidiate. llama2 needs about 10-20 seconds to boot up, then it answers. it would be nice to remove that delay.

**Comment by dangminhduc1101** [comment]
@tjbck  is this even doable? I don't think the REST api allows us to do this.

**Comment by tjbck** [comment]
Related: https://github.com/ollama-webui/ollama-webui/issues/596
