### ISSUE TITLE
Route for chat appears to be missing

### ISSUE THREAD

**Issue by Flowm** [ollama-webui/ollama-webui-lite#9]
# Bug Report

## Description

**Bug Summary:**
When starting the app with `npm run dev` as described in the readme the chat works fine, but clicking on any chat in the right navbar results in a 404 page.

It looks like the `/c/[id]` route is not registed with svelte (like it is in ollma-webui https://github.com/ollama-webui/ollama-webui/blob/main/src/routes/(app)/c/%5Bid%5D/%2Bpage.svelte)

Video: https://github.com/ollama-webui/ollama-webui-lite/assets/1117666/d887099d-643e-4a57-96ff-605b1370e80e

**Steps to Reproduce:**
Click on any chat on left sidebar.

**Expected Behavior:**
The chat opens.

**Actual Behavior:**
An error page is rendered.

## Environment

- **Operating System:** macOS 14.2.1
- **Browser (if applicable):** Chrome 120.0.6099.199

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I have reviewed the troubleshooting.md document.
- [X] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
app.598939ed.js:1 Error: Not found: /c/1dbf8f8c-43a2-4636-b571-fcaa5755b44c
    at ce (start.9029f0de.js:1:14918)
    at re (start.9029f0de.js:1:8155)
    at Object.goto (start.9029f0de.js:1:18073)
    at Module.Nt (start.9029f0de.js:3:1691)
    at 1dbf8f8c-43a2-4636-b571-fcaa5755b44c:42:11
```

**Screenshots (if applicable):**
<img width="868" alt="image" src="https://github.com/ollama-webui/ollama-webui-lite/assets/1117666/6de9f2ef-01b1-4ea9-b885-5f7be53a5a72">

## Installation Method

Running the dev server as described in the readme

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by dangminhduc1101** [comment]
Thanks for the issue, I have encountered this bug when breaking down the app too, but didn't look into it. It's an error on my end to delete the `c/[id]` route when breaking it down, will fix it now.

**Comment by dangminhduc1101** [comment]
Fixed:
![preview](https://github.com/ollama-webui/ollama-webui-lite/assets/73714655/de71d66c-abc4-4f7a-b54c-a5c535c24a8e)

**Comment by dangminhduc1101** [comment]
Fixed with latest merge:
![Screenshot from 2024-01-07 21-46-58](https://github.com/ollama-webui/ollama-webui-lite/assets/73714655/645fe5aa-a4fd-4b15-afff-aec2feb715ff)
